version: '3.7'
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=ohbug
      - POSTGRES_PASSWORD=ohbug
      - POSTGRES_DB=ohbug
    hostname: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    hostname: redis
    ports:
      - '6379:6379'

  app:
    image: ohbug/ohbug-ce:latest
    restart: always
    ports:
      - '3000:3000'
      - '6660:6660'
    volumes:
      - ./ohbug.config.yml:/app/ohbug.config.yml
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - '3001:3001'
      - '6661:6661'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
      - ./secrets:/app/secrets
    depends_on:
      - app
