version: '3.7'

services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=ohbug
      - POSTGRES_PASSWORD=ohbug
      - POSTGRES_DB=ohbug
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'

volumes:
  pgdata: {}
