http:
  url: http://localhost:3000

db:
  postgres:
    host: localhost
    port: 5432
    database: ohbug
    user: ohbug
    password: ohbug

  redis:
    host: localhost
    port: 6379

secret:
  apikey: ohbug-apikey-s3cret
  session: ohbug-session-s3cret
