http:
  url: http://localhost:3000

db:
  postgres:
    host: localhost
    port: 5432
    database: ohbug
    user: ohbug
    password: ohbug

secret:
  apikey: ohbug-apikey-s3cret
  session: ohbug-session-s3cret

oauth:
  github:
    clientId: ''
    clientSecret: ''

# email:
#   server:
#     host: smtp.example.com
#     port: 465
#     auth:
#       user: username
#       pass: password
#   from: admin@ohbug.net
