import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta
          content="Generated by create next app"
          name="description"
        />
        <link
          href="/favicon.ico"
          rel="icon"
        />
      </Head>

      <main>
        <Link href="/issues"><a>go to issues</a></Link>
      </main>
    </div>
  )
}

export default Home
