import type { Setting } from '@prisma/client'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Login from '~/components/loginButton'
import { serviceGetSetting } from '~/services/bootstrap'
import { serviceGetProjects } from '~/services/projects'

interface Props {
  setting: Setting | null
}

export const getServerSideProps: GetServerSideProps<Props> = async() => {
  const setting = await serviceGetSetting()
  if (!setting) {
    return {
      redirect: {
        destination: '/bootstrap',
        permanent: false,
      },
    }
  }
  const projects = await serviceGetProjects()
  if (!projects || !projects.length) {
    return {
      redirect: {
        destination: '/create-project',
        permanent: false,
      },
    }
  }
  return { props: { setting } }
}

const Home: NextPage<Props> = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta
          content="Generated by create next app"
          name="description"
        />
        <link
          href="/favicon.ico"
          rel="icon"
        />
      </Head>

      <main>
        <div><Link href="/issues"><a>go to issues</a></Link></div>

        <Login />
      </main>
    </div>
  )
}

export default Home
